language: python

before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b
    - . /home/travis/miniconda3/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda config --add channels r
    - conda create --yes -n test
    - conda activate test
    - conda install -y pycodestyle
    - conda install --yes python=3.6
    - conda install matplotlib --yes
    - python gen_data.py --key_type string --value_type string --sorted False --outfile rand.txt
    - python gen_data.py --key_type string --value_type string --sorted True --outfile sorted.txt
script:
    - pycodestyle *.py
    - python -m unittest test_binary_tree.py
    - python -m unittest test_insert_key_value_pairs.py
    - python -m unittest test_avl_tree.py
    - python -m unittest test_gen_data.py